variables:
  RUST_BACKTRACE: full

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - checkout: self
    submodules: true
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
  - script: |
      git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      #echo "##vso[task.setvariable variable=PATH;]$PATH:$AGENT_BUILDDIRECTORY/depot_tools"
      echo "##vso[task.prependpath]$AGENT_BUILDDIRECTORY/depot_tools"
      echo `which ninja`
      echo `which gn`
    displayName: Install depot_tools
  - script: cargo test -vv --all
    displayName: Cargo test
