variables:
  RUST_BACKTRACE: full

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - checkout: self
    submodules: true
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
  - script: |
      git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git --depth=1
      echo "##vso[task.prependpath]$(system.defaultWorkingDirectory)/depot_tools"
    displayName: Install depot_tools
  - script: |
      echo "ninja $(which ninja) gn $(which gn)"
      cargo test -vv --all
    displayName: Cargo test
