variables:
  RUST_BACKTRACE: full

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - checkout: self
    submodules: true
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
  - script: |
      echo "hello"
      git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      echo "world"
      depot_tools/ninja
      echo "##vso[task.prependpath]$AGENT_BUILD_DIRECTORY/depot_tools"
      gn help
      echo "done"
      #depot_tools/gn
      #git clone -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" https://chromium.googlesource.com/chromium/tools/depot_tools.git
      #echo `which ninja`
      #echo `which gn`
      #echo "##vso[task.setvariable variable=PATH;]$PATH:$AGENT_BUILDDIRECTORY/depot_tools"
    displayName: Install depot_tools
  - script: cargo test -vv --all
    displayName: Cargo test
